<?php
ini_set('display_errors'        , 'On');
ini_set('display_startup_errors', 'On');
ini_set('error_reporting'       , 'E_ALL | E_STRICT');
ini_set('track_errors'          , 'On');
ini_set('display_errors'        , 1);
error_reporting(E_ALL);
include "url.php";

echo "<h1>example 1</h1>";
echo "<h3>make_url(\"https://ermile.tejarak.com:80/fa/cp/tools/sitemap/ch=1/sa=2?run=true&ex=0\")</h3>";
var_dump(\lib\url::make_url("https://ermile.tejarak.com:80/fa/cp/tools/sitemap/ch=1/sa=2?run=true&ex=0"));
echo "<h3>config()</h3>";
var_dump(\lib\url::config());
echo "<h3>full()</h3>";
var_dump(\lib\url::full());
echo "<h3>path()</h3>";
var_dump(\lib\url::path());
echo "<h3>base()</h3>";
var_dump(\lib\url::base());
echo "<h3>dir()</h3>";
var_dump(\lib\url::dir());
echo "<h4>dir(0)</h4>";
var_dump(\lib\url::dir(0));
echo "<h4>dir(1)</h4>";
var_dump(\lib\url::dir(1));
echo "<h4>dir(2)</h4>";
var_dump(\lib\url::dir(2));
echo "<h4>dir(3)</h4>";
var_dump(\lib\url::dir(3));
echo "<h4>dir(4)</h4>";
var_dump(\lib\url::dir(4));
echo "<h3>protocol()</h3>";
var_dump(\lib\url::protocol());
echo "<h3>host()</h3>";
var_dump(\lib\url::host());
echo "<h3>sub_domain()</h3>";
var_dump(\lib\url::sub_domain());
echo "<h3>domain()</h3>";
var_dump(\lib\url::domain());
echo "<h3>root()</h3>";
var_dump(\lib\url::root());
echo "<h3>tld()</h3>";
var_dump(\lib\url::tld());
echo "<h3>port()</h3>";
var_dump(\lib\url::port());
echo "<h3>lang()</h3>";
var_dump(\lib\url::lang());
echo "<h3>content()</h3>";
var_dump(\lib\url::content());
echo "<h3>module()</h3>";
var_dump(\lib\url::module());
echo "<h3>child()</h3>";
var_dump(\lib\url::child());
echo "<h3>property()</h3>";
var_dump(\lib\url::property());
echo "<h4>property('ch')</h4>";
var_dump(\lib\url::property("ch"));
echo "<h4>property('sa')</h4>";
var_dump(\lib\url::property("sa"));
echo "<h3>query()</h3>";
var_dump(\lib\url::query());
echo "<h4>query('run')</h4>";
var_dump(\lib\url::query("run"));
echo "<h4>query('ex')</h4>";
var_dump(\lib\url::query("ex"));

echo "<h1>example 2</h1>";
echo "<h3>make_url(\"https://192.168.1.2:80/fa/cp/tools/sitemap/ch=1/sa=2?run=true&ex=0\")</h3>";
var_dump(\lib\url::make_url("https://192.168.1.2:80/fa/cp/tools/sitemap/ch=1/sa=2?run=true&ex=0"));
echo "<h3>config()</h3>";
var_dump(\lib\url::config());
echo "<h3>full()</h3>";
var_dump(\lib\url::full());
echo "<h3>path()</h3>";
var_dump(\lib\url::path());
echo "<h3>base()</h3>";
var_dump(\lib\url::base());
echo "<h3>dir()</h3>";
var_dump(\lib\url::dir());
echo "<h4>dir(0)</h4>";
var_dump(\lib\url::dir(0));
echo "<h4>dir(1)</h4>";
var_dump(\lib\url::dir(1));
echo "<h4>dir(2)</h4>";
var_dump(\lib\url::dir(2));
echo "<h4>dir(3)</h4>";
var_dump(\lib\url::dir(3));
echo "<h4>dir(4)</h4>";
var_dump(\lib\url::dir(4));
echo "<h3>protocol()</h3>";
var_dump(\lib\url::protocol());
echo "<h3>host()</h3>";
var_dump(\lib\url::host());
echo "<h3>sub_domain()</h3>";
var_dump(\lib\url::sub_domain());
echo "<h3>domain()</h3>";
var_dump(\lib\url::domain());
echo "<h3>root()</h3>";
var_dump(\lib\url::root());
echo "<h3>tld()</h3>";
var_dump(\lib\url::tld());
echo "<h3>port()</h3>";
var_dump(\lib\url::port());
echo "<h3>lang()</h3>";
var_dump(\lib\url::lang());
echo "<h3>content()</h3>";
var_dump(\lib\url::content());
echo "<h3>module()</h3>";
var_dump(\lib\url::module());
echo "<h3>child()</h3>";
var_dump(\lib\url::child());
echo "<h3>property()</h3>";
var_dump(\lib\url::property());
echo "<h4>property('ch')</h4>";
var_dump(\lib\url::property("ch"));
echo "<h4>property('sa')</h4>";
var_dump(\lib\url::property("sa"));
echo "<h3>query()</h3>";
var_dump(\lib\url::query());
echo "<h4>query('run')</h4>";
var_dump(\lib\url::query("run"));
echo "<h4>query('ex')</h4>";
var_dump(\lib\url::query("ex") );


echo "<h1>example 3</h1>";
echo "<h3>make_url(\"https://tejarak.com/cp/tools/sitemap/ch=1/sa=2\")</h3>";
var_dump(\lib\url::make_url("https://tejarak.com/cp/tools/sitemap/ch=1/sa=2"));
echo "<h3>config()</h3>";
var_dump(\lib\url::config());
echo "<h3>full()</h3>";
var_dump(\lib\url::full());
echo "<h3>path()</h3>";
var_dump(\lib\url::path());
echo "<h3>base()</h3>";
var_dump(\lib\url::base());
echo "<h3>dir()</h3>";
var_dump(\lib\url::dir());
echo "<h4>dir(0)</h4>";
var_dump(\lib\url::dir(0));
echo "<h4>dir(1)</h4>";
var_dump(\lib\url::dir(1));
echo "<h4>dir(2)</h4>";
var_dump(\lib\url::dir(2));
echo "<h4>dir(3)</h4>";
var_dump(\lib\url::dir(3));
echo "<h4>dir(4)</h4>";
var_dump(\lib\url::dir(4));
echo "<h3>protocol()</h3>";
var_dump(\lib\url::protocol());
echo "<h3>host()</h3>";
var_dump(\lib\url::host());
echo "<h3>sub_domain()</h3>";
var_dump(\lib\url::sub_domain());
echo "<h3>domain()</h3>";
var_dump(\lib\url::domain());
echo "<h3>root()</h3>";
var_dump(\lib\url::root());
echo "<h3>tld()</h3>";
var_dump(\lib\url::tld());
echo "<h3>port()</h3>";
var_dump(\lib\url::port());
echo "<h3>lang()</h3>";
var_dump(\lib\url::lang());
echo "<h3>content()</h3>";
var_dump(\lib\url::content());
echo "<h3>module()</h3>";
var_dump(\lib\url::module());
echo "<h3>child()</h3>";
var_dump(\lib\url::child());
echo "<h3>property()</h3>";
var_dump(\lib\url::property());
echo "<h4>property('ch')</h4>";
var_dump(\lib\url::property("ch"));
echo "<h4>property('sa')</h4>";
var_dump(\lib\url::property("sa"));
echo "<h3>query()</h3>";
var_dump(\lib\url::query());


echo "<h1>example 4</h1>";
echo "<h3>make_url(\"http://tejarak.com/cp/tools/sitemap\")</h3>";
var_dump(\lib\url::make_url("http://tejarak.com/cp/tools/sitemap"));
echo "<h3>config()</h3>";
var_dump(\lib\url::config());
echo "<h3>full()</h3>";
var_dump(\lib\url::full());
echo "<h3>path()</h3>";
var_dump(\lib\url::path());
echo "<h3>base()</h3>";
var_dump(\lib\url::base());
echo "<h3>dir()</h3>";
var_dump(\lib\url::dir());
echo "<h4>dir(0)</h4>";
var_dump(\lib\url::dir(0));
echo "<h4>dir(1)</h4>";
var_dump(\lib\url::dir(1));
echo "<h4>dir(2)</h4>";
var_dump(\lib\url::dir(2));
echo "<h4>dir(3)</h4>";
var_dump(\lib\url::dir(3));
echo "<h3>protocol()</h3>";
var_dump(\lib\url::protocol());
echo "<h3>host()</h3>";
var_dump(\lib\url::host());
echo "<h3>sub_domain()</h3>";
var_dump(\lib\url::sub_domain());
echo "<h3>domain()</h3>";
var_dump(\lib\url::domain());
echo "<h3>root()</h3>";
var_dump(\lib\url::root());
echo "<h3>tld()</h3>";
var_dump(\lib\url::tld());
echo "<h3>port()</h3>";
var_dump(\lib\url::port());
echo "<h3>lang()</h3>";
var_dump(\lib\url::lang());
echo "<h3>content()</h3>";
var_dump(\lib\url::content());
echo "<h3>module()</h3>";
var_dump(\lib\url::module());
echo "<h3>child()</h3>";
var_dump(\lib\url::child());
echo "<h3>property()</h3>";
var_dump(\lib\url::property());
echo "<h3>query()</h3>";
var_dump(\lib\url::query());


echo "<h1>example 5</h1>";
echo "<h3>make_url(\"http://tejarak.com\")</h3>";
var_dump(\lib\url::make_url("http://tejarak.com"));
echo "<h3>config()</h3>";
var_dump(\lib\url::config());
echo "<h3>full()</h3>";
var_dump(\lib\url::full());
echo "<h3>path()</h3>";
var_dump(\lib\url::path());
echo "<h3>base()</h3>";
var_dump(\lib\url::base());
echo "<h3>dir()</h3>";
var_dump(\lib\url::dir());
echo "<h3></h3>";
var_dump(\lib\url::dir(0));
echo "<h3>protocol()</h3>";
var_dump(\lib\url::protocol());
echo "<h3>host()</h3>";
var_dump(\lib\url::host());
echo "<h3>sub_domain()</h3>";
var_dump(\lib\url::sub_domain());
echo "<h3>domain()</h3>";
var_dump(\lib\url::domain());
echo "<h3>root()</h3>";
var_dump(\lib\url::root());
echo "<h3>tld()</h3>";
var_dump(\lib\url::tld());
echo "<h3>port()</h3>";
var_dump(\lib\url::port());
echo "<h3>lang()</h3>";
var_dump(\lib\url::lang());
echo "<h3>content()</h3>";
var_dump(\lib\url::content());
echo "<h3>module()</h3>";
var_dump(\lib\url::module());
echo "<h3>child()</h3>";
var_dump(\lib\url::child());
echo "<h3>property()</h3>";
var_dump(\lib\url::property());
echo "<h3>query()</h3>";
var_dump(\lib\url::query());


echo "<h1>example 6</h1>";
echo "<h3>make_url()</h3>";
var_dump(\lib\url::make_url());
echo "<h3>config()</h3>";
var_dump(\lib\url::config());
echo "<h3>full()</h3>";
var_dump(\lib\url::full());
echo "<h3>path()</h3>";
var_dump(\lib\url::path());
echo "<h3>base()</h3>";
var_dump(\lib\url::base());
echo "<h3>dir()</h3>";
var_dump(\lib\url::dir());
echo "<h3></h3>";
var_dump(\lib\url::dir(0));
echo "<h3>protocol()</h3>";
var_dump(\lib\url::protocol());
echo "<h3>host()</h3>";
var_dump(\lib\url::host());
echo "<h3>sub_domain()</h3>";
var_dump(\lib\url::sub_domain());
echo "<h3>domain()</h3>";
var_dump(\lib\url::domain());
echo "<h3>root()</h3>";
var_dump(\lib\url::root());
echo "<h3>tld()</h3>";
var_dump(\lib\url::tld());
echo "<h3>port()</h3>";
var_dump(\lib\url::port());
echo "<h3>lang()</h3>";
var_dump(\lib\url::lang());
echo "<h3>content()</h3>";
var_dump(\lib\url::content());
echo "<h3>module()</h3>";
var_dump(\lib\url::module());
echo "<h3>child()</h3>";
var_dump(\lib\url::child());
echo "<h3>property()</h3>";
var_dump(\lib\url::property());
echo "<h3>query()</h3>";
var_dump(\lib\url::query());
