<?php
ini_set('display_errors'        , 'On');
ini_set('display_startup_errors', 'On');
ini_set('error_reporting'       , 'E_ALL | E_STRICT');
ini_set('track_errors'          , 'On');
ini_set('display_errors'        , 1);
error_reporting(E_ALL);
include "url.php";

echo "<h1>example 1</h1>";
echo "<h3>make_url(\"https://ermile.tejarak.com:80/fa/cp/tools/sitemap/ch=1/sa=2?run=true&ex=0\")</h3>";
var_dump(\lib\url::make_url("https://ermile.tejarak.com:80/fa/cp/tools/sitemap/ch=1/sa=2?run=true&ex=0"));

echo "<h3>get_array()</h3>";
var_dump(\lib\url::get_array());

echo "<h3>set_protocol('http')</h3>";
var_dump(\lib\url::set_protocol('http'));
echo "<h3>set_sub_domain('javad')</h3>";
var_dump(\lib\url::set_sub_domain('javad'));
echo "<h3>set_root('geeksesi')</h3>";
var_dump(\lib\url::set_root('geeksesi'));
echo "<h3>set_tld('xyz')</h3>";
var_dump(\lib\url::set_tld("xyz"));
echo "<h3>set_port('88')</h3>";
var_dump(\lib\url::set_port('88'));
echo "<h3>set_lang('az')</h3>";
var_dump(\lib\url::set_lang('az'));
echo "<h3>set_content('su')</h3>";
var_dump(\lib\url::set_content('su'));
echo "<h3>set_module('test')</h3>";
var_dump(\lib\url::set_module('test','false'));
echo "<h3>set_child('sf')</h3>";
var_dump(\lib\url::set_child('sf','none'));
echo "<h4>set_property('ch')</h4>";
var_dump(\lib\url::set_property('ch','javad'));
echo "<h4>set_property('sa',1)</h4>";
var_dump(\lib\url::set_property('sa',1));
echo "<h4>set_query('run','+2')</h4>";
var_dump(\lib\url::set_query('run',"+2"));
echo "<h4>set_query('fo','bar')</h4>";
var_dump(\lib\url::set_query('fo','bar'));
echo "<h3>get_array()</h3>";
var_dump(\lib\url::get_array());
echo "<h3>full()</h3>";
var_dump(\lib\url::full());
echo "<h3>path()</h3>";
var_dump(\lib\url::path());
echo "<h3>base()</h3>";
var_dump(\lib\url::base());
echo "<h3>dir()</h3>";
var_dump(\lib\url::dir());
echo "<h4>dir(0)</h4>";
var_dump(\lib\url::dir(0));
echo "<h4>dir(1)</h4>";
var_dump(\lib\url::dir(1));
echo "<h4>dir(2)</h4>";
var_dump(\lib\url::dir(2));
echo "<h4>dir(3)</h4>";
var_dump(\lib\url::dir(3));
echo "<h4>dir(4)</h4>";
var_dump(\lib\url::dir(4));


echo "<h1>example 2</h1>";
echo "<h3>make_url(\"https://tejarak.com/cp/tools/sitemap/ch=1\")</h3>";
var_dump(\lib\url::make_url("https://tejarak.com/cp/tools/sitemap/ch=1"));
echo "<h3>get_array()</h3>";
var_dump(\lib\url::get_array());

echo "<h3>set_protocol('http')</h3>";
var_dump(\lib\url::set_protocol('http'));
echo "<h3>set_sub_domain('javad')</h3>";
var_dump(\lib\url::set_sub_domain('azvir'));
echo "<h3>set_root('geeksesi')</h3>";
var_dump(\lib\url::set_root('geeksesi'));
echo "<h3>set_tld('xyz')</h3>";
var_dump(\lib\url::set_tld("xyz"));
echo "<h3>set_port('88')</h3>";
var_dump(\lib\url::set_port('88'));
echo "<h3>set_lang('az')</h3>";
var_dump(\lib\url::set_lang('az'));
echo "<h3>set_content('su')</h3>";
var_dump(\lib\url::set_content('sm'));
echo "<h3>set_module('test')</h3>";
var_dump(\lib\url::set_module('test','false'));
echo "<h3>set_child('sf')</h3>";
var_dump(\lib\url::set_child('sf','none'));
echo "<h4>set_property('ch')</h4>";
var_dump(\lib\url::set_property('ch','javad'));
echo "<h4>set_property('sa','12')</h4>";
var_dump(\lib\url::set_property('sm','12'));
echo "<h4>set_query('run','+2')</h4>";
var_dump(\lib\url::set_query('run',"+2"));
echo "<h4>set_query('fo','bar')</h4>";
var_dump(\lib\url::set_query('fo','bar'));
echo "<h4>set_query('fo','bar')</h4>";
var_dump(\lib\url::set_query('bar','foo'));
echo "<h3>get_array()</h3>";
var_dump(\lib\url::get_array());
echo "<h3>full()</h3>";
var_dump(\lib\url::full());
echo "<h3>path()</h3>";
var_dump(\lib\url::path());
echo "<h3>base()</h3>";
var_dump(\lib\url::base());
echo "<h3>dir()</h3>";
var_dump(\lib\url::dir());
echo "<h4>dir(0)</h4>";
var_dump(\lib\url::dir(0));
echo "<h4>dir(1)</h4>";
var_dump(\lib\url::dir(1));
echo "<h4>dir(2)</h4>";
var_dump(\lib\url::dir(2));
echo "<h4>dir(3)</h4>";
var_dump(\lib\url::dir(3));
echo "<h4>dir(4)</h4>";
var_dump(\lib\url::dir(4));

echo "<h1>example 3</h1>";
echo "<h3>make_url()</h3>";
var_dump(\lib\url::make_url());
echo "<h3>get_array()</h3>";
var_dump(\lib\url::get_array());

echo "<h3>set_protocol('http')</h3>";
var_dump(\lib\url::set_protocol('https'));
echo "<h3>set_root('geeksesi')</h3>";
var_dump(\lib\url::set_root('geeksesi'));
echo "<h3>set_tld('xyz')</h3>";
var_dump(\lib\url::set_tld("xyz"));
echo "<h3>set_port('88')</h3>";
var_dump(\lib\url::set_port('88'));
echo "<h3>set_lang('az')</h3>";
var_dump(\lib\url::set_lang('az'));
echo "<h3>set_module('test')</h3>";
var_dump(\lib\url::set_module('test'));
echo "<h4>set_query('fo','bar')</h4>";
var_dump(\lib\url::set_query('fo','bar'));
echo "<h3>get_array()</h3>";
var_dump(\lib\url::get_array());
echo "<h3>full()</h3>";
var_dump(\lib\url::full());
echo "<h3>path()</h3>";
var_dump(\lib\url::path());
echo "<h3>base()</h3>";
var_dump(\lib\url::base());
echo "<h3>dir()</h3>";
var_dump(\lib\url::dir());
echo "<h4>dir(0)</h4>";
var_dump(\lib\url::dir(0));
echo "<h4>dir(1)</h4>";
var_dump(\lib\url::dir(1));
echo "<h4>dir(2)</h4>";
var_dump(\lib\url::dir(2));
echo "<h4>dir(3)</h4>";
var_dump(\lib\url::dir(3));
echo "<h4>ip(3)</h4>";
var_dump(\lib\url::ip());
echo "<h3>get_array()</h3>";
var_dump(\lib\url::get_array());